FROM alpine:3.23

LABEL org.opencontainers.image.source="https://github.com/ponylang/ponyup"

RUN apk add --update --no-cache \
     binutils-gold \
     build-base \
     clang \
     curl \
     git \
     libressl-dev \
     make
