#
# Pull Request tasks
#

task:
  only_if: $CIRRUS_PR != ''

  freebsd_instance:
    image: freebsd-13-1-release-amd64

  name: "PR: x86-64-unknown-freebsd-13.1"

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - pkg install -y bash git gmake
    - bash .ci-scripts/freebsd-13.1-install-pony-tools.bash

  test_script:
    - export PATH="/tmp/corral/bin:/tmp/ponyc/bin/:$PATH"
    - gmake test ssl=1.1.x

task:
  only_if: $CIRRUS_PR != ''

  freebsd_instance:
    image: freebsd-13-1-release-amd64

  name: "PR: Test bootstrapping on FreeBSD 13.1"

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - echo "IGNORE_OSVERSION = yes" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y bash git gmake
    - bash .ci-scripts/freebsd-13.1-install-pony-tools.bash

  test_script:
    - MAKE=gmake .ci-scripts/test-bootstrap.sh

task:
  only_if: $CIRRUS_PR != ''

  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:13.3.1

  name: "PR: arm64-apple-darwin"

  install_script:
    - bash .ci-scripts/MacOS-arm64-install-pony-tools.bash release

  test_script:
    - export PATH="/tmp/corral/bin:/tmp/ponyc/bin/:$PATH"
    - make test

task:
  only_if: $CIRRUS_PR != ''

  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:13.3.1

  name: "PR: Test bootstrapping on MacOS"

  install_script:
    - bash .ci-scripts/MacOS-arm64-install-pony-tools.bash release

  test_script:
    - export PATH="/tmp/corral/bin:/tmp/ponyc/bin/:$PATH"
    - SSL=0.9.0 .ci-scripts/test-bootstrap.sh

#
# Nightly build tasks
#

task:
  only_if: $CIRRUS_CRON == "nightly"

  freebsd_instance:
    image: freebsd-13-1-release-amd64

  name: "nightly: x86-64-unknown-freebsd-13.1"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[d15be7fc411420cf7199bb36e5b7d8d4493bbeda67c06e32a61c9e2889bc7429bca6f5176d793b915ca891b18c8dfa1f]
    GITHUB_REPOSITORY: ponylang/ponyup

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - python3 -m ensurepip --upgrade
    - python3 -m pip install cloudsmith-cli
    - pkg install -y bash gmake git
    - bash .ci-scripts/freebsd-13.1-install-pony-tools.bash

  nightly_script:
    - bash .ci-scripts/release/x86-64-unknown-freebsd-13.1-nightly.bash

task:
  only_if: $CIRRUS_CRON == "nightly"

  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:13.3.1

  name: "nightly: arm64-apple-darwin"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[d15be7fc411420cf7199bb36e5b7d8d4493bbeda67c06e32a61c9e2889bc7429bca6f5176d793b915ca891b18c8dfa1f]
    GITHUB_REPOSITORY: ponylang/ponyup

  install_script:
    - brew install coreutils
    - pip3 install --upgrade cloudsmith-cli
    - bash .ci-scripts/MacOS-arm64-install-pony-tools.bash release

  nightly_script:
    - export PATH="/tmp/corral/bin:/tmp/ponyc/bin/:/Users/admin/Library/Python/3.8/bin:$PATH"
    - bash .ci-scripts/release/arm64-apple-darwin-nightly.bash

#
# Release build tasks
#

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  freebsd_instance:
    image: freebsd-13-1-release-amd64

  name: "release: x86-64-unknown-freebsd-13.1"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[d15be7fc411420cf7199bb36e5b7d8d4493bbeda67c06e32a61c9e2889bc7429bca6f5176d793b915ca891b18c8dfa1f]
    GITHUB_REPOSITORY: ponylang/ponyup

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - python3 -m ensurepip --upgrade
    - python3 -m pip install cloudsmith-cli
    - pkg install -y bash gmake git
    - bash .ci-scripts/freebsd-13.1-install-pony-tools.bash

  release_script:
    - bash .ci-scripts/release/x86-64-unknown-freebsd-13.1-release.bash

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:13.3.1

  name: "release: arm64-apple-darwin"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[d15be7fc411420cf7199bb36e5b7d8d4493bbeda67c06e32a61c9e2889bc7429bca6f5176d793b915ca891b18c8dfa1f]
    GITHUB_REPOSITORY: ponylang/ponyup

  install_script:
    - brew install coreutils
    - pip3 install --upgrade cloudsmith-cli
    - bash .ci-scripts/MacOS-arm64-install-pony-tools.bash release

  release_script:
    - export PATH="/tmp/corral/bin:/tmp/ponyc/bin/:/Users/admin/Library/Python/3.8/bin:$PATH"
    - bash .ci-scripts/release/arm64-apple-darwin-release.bash
