FROM alpine:3.12

RUN apk update \
  && apk upgrade \
  && apk add --update \
     binutils-gold \
     build-base \
     clang \
     curl \
     git \
     libexecinfo \
     libexecinfo-static \
     libressl-dev \
     make
