FROM alpine:3.16

RUN apk add --update --no-cache \
     binutils-gold \
     build-base \
     clang \
     curl \
     git \
     libexecinfo \
     libexecinfo-static \
     libressl-dev \
     make
