name: arm64 macOS ponyc update breakage test

on:
  repository_dispatch:
    types: [ponyc-arm64-macos-nightly-released]

jobs:
  vs-ponyc-main-macos:
    name: Verify main against ponyc main on arm64 macOS
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: install pony tools
        run: bash .ci-scripts/macOS-arm64-install-pony-tools.bash nightly
      - name: Test with the most recent ponyc release
        run: |
          export PATH=/tmp/corral/bin/:/tmp/ponyc/bin/:$PATH
          make test
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.
