name: x86-64 macOS ponyc update breakage test

on:
  repository_dispatch:
    types: [ponyc-x86_64-macos-nightly-released]

jobs:
  vs-ponyc-main-macos:
    name: Verify main against ponyc main on x86-64 macOS
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: install pony tools
        run: bash .ci-scripts/macOS-x86-install-pony-tools.bash nightly
      # we can't turn this on until we are able to pass the tests
      # that requires a couple of macos on intel ponyc releases
      # - name: Test with the most recent ponyc release
      #   run: |
      #     export PATH=/tmp/corral/bin/:/tmp/ponyc/bin/:$PATH
      #     make test
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.
